// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBj13EH-BQGGhEl8qnd0monaOU90tqUtg',
    appId: '1:894802445528:web:aa3695f84cbd51c5fc03ad',
    messagingSenderId: '894802445528',
    projectId: 'i-extract',
    authDomain: 'i-extract.firebaseapp.com',
    storageBucket: 'i-extract.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMyLT4Idi-ySUxLIQS4DXKtXrD_BpHuw',
    appId: '1:894802445528:android:44122b8c3296d94afc03ad',
    messagingSenderId: '894802445528',
    projectId: 'i-extract',
    storageBucket: 'i-extract.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGxfXnwbXBudvdxG6QVyn1KKkUA-rMZo',
    appId: '1:894802445528:ios:1ad0ecc79843f94bfc03ad',
    messagingSenderId: '894802445528',
    projectId: 'i-extract',
    storageBucket: 'i-extract.appspot.com',
    iosClientId: '894802445528-7365qok2u5cve3kruc4gtunh49dannbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixmyenglish',
  );
}
